import React, { useState } from 'react';
import { useAppContext } from '../App';
import type { AppState, TransactionType, Budget, FinancialGoal, Bill, Debt, AppLayout, AppFont, AccentColor } from '../types';
import { formatCurrency } from '../types';
import { Card, Button, Modal, CurrencyInput, PlusIcon, TrashIcon, EditIcon, CheckCircleIcon, SunIcon, MoonIcon, PaletteIcon } from './ui';

export const Settings: React.FC = () => {
    const { state, setState, activeLayout, activeFont, activeAccent, colorScheme, setColorScheme, updateUserSettings } = useAppContext();
    const [activeTab, setActiveTab] = useState('umum');
    const tabs = [{ id: 'umum', label: 'Umum' }, { id: 'anggaran', label: 'Anggaran' }, { id: 'target', label: 'Target' }, { id: 'dompet', label: 'Dompet' }, { id: 'tagihan', label: 'Tagihan' }, { id: 'utang', label: 'Utang' }];

    const handleSave = (itemType: keyof AppState, item: any) => setState(prev => { const items = prev[itemType] as any[]; if (!Array.isArray(items)) return prev; const index = items.findIndex((i: any) => i.id === item.id); let newItems; if (index > -1) newItems = items.map(c => c.id === item.id ? item : c); else newItems = [...items, item]; return { ...prev, [itemType]: newItems }; });
    const handleDelete = (itemType: keyof AppState, id: string) => setState(prev => { const items = prev[itemType] as any[]; if (!Array.isArray(items)) return prev; return { ...prev, [itemType]: items.filter((i: any) => i.id !== id) }; });

    const CategorySettings = () => {
        const [isModalOpen, setIsModalOpen] = useState(false);
        const [name, setName] = useState('');
        const [type, setType] = useState<TransactionType>('expense');
        const handleAddCategory = () => { if (!name) return; setState(prev => ({ ...prev, categories: [...prev.categories, { id: `cat-${new Date().getTime()}`, name, type }] })); setName(''); setIsModalOpen(false); };
        const handleDeleteCategory = (id: string) => { if (state.budgets.some(b => b.categoryId === id)) { alert('Tidak dapat menghapus kategori yang digunakan dalam anggaran. Hapus anggaran terlebih dahulu.'); return; } if (window.confirm('Apakah Anda yakin ingin menghapus kategori ini?')) setState(prev => ({ ...prev, categories: prev.categories.filter(c => c.id !== id) })); };
        const openAddModal = (initialType: TransactionType) => { setType(initialType); setName(''); setIsModalOpen(true); };
        return (<><div className="grid grid-cols-1 md:grid-cols-2 gap-6"><Card><div className="flex justify-between items-center mb-4"><h3 className="text-lg font-semibold">Kategori Pemasukan</h3><Button onClick={() => openAddModal('income')}><PlusIcon className="w-4 h-4 mr-1"/> Tambah</Button></div><ul className="space-y-2">{state.categories.filter(c => c.type === 'income').map(c => <li key={c.id} className="flex justify-between items-center p-2 bg-slate-100 dark:bg-slate-700 rounded"><span>{c.name}</span><button onClick={() => handleDeleteCategory(c.id)}><TrashIcon className="w-4 h-4 text-red-500"/></button></li>)}</ul></Card><Card><div className="flex justify-between items-center mb-4"><h3 className="text-lg font-semibold">Kategori Pengeluaran</h3><Button onClick={() => openAddModal('expense')}><PlusIcon className="w-4 h-4 mr-1"/> Tambah</Button></div><ul className="space-y-2">{state.categories.filter(c => c.type === 'expense').map(c => <li key={c.id} className="flex justify-between items-center p-2 bg-slate-100 dark:bg-slate-700 rounded"><span>{c.name}</span><button onClick={() => handleDeleteCategory(c.id)}><TrashIcon className="w-4 h-4 text-red-500"/></button></li>)}</ul></Card></div><Modal isOpen={isModalOpen} onClose={() => setIsModalOpen(false)} title="Tambah Kategori Baru"><div className="p-6 space-y-4"><input type="text" value={name} onChange={e => setName(e.target.value)} placeholder="Nama Kategori" className="block w-full px-3 py-2 text-sm border border-slate-300 rounded-md bg-white dark:bg-slate-700 dark:border-slate-600 dark:text-white placeholder-slate-400 dark:placeholder-slate-400"/><select value={type} onChange={e => setType(e.target.value as TransactionType)} className="block w-full px-3 py-2 text-sm border border-slate-300 rounded-md bg-white dark:bg-slate-700 dark:border-slate-600 dark:text-white"><option value="expense">Pengeluaran</option><option value="income">Pemasukan</option></select><Button onClick={handleAddCategory} className="w-full">Simpan</Button></div></Modal></>);
    };
    const BudgetSettings = () => {
        const [isModalOpen, setIsModalOpen] = useState(false);
        const [categoryId, setCategoryId] = useState('');
        const [amount, setAmount] = useState(0);
        const [editingBudget, setEditingBudget] = useState<Budget | null>(null);
        const expenseCategories = state.categories.filter(c => c.type === 'expense');
        const openEditModal = (b: Budget) => { setEditingBudget(b); setCategoryId(b.categoryId); setAmount(b.amount); setIsModalOpen(true); };
        const openAddModal = () => { setEditingBudget(null); setCategoryId(''); setAmount(0); setIsModalOpen(true); };
        const handleSaveBudget = () => { if (!categoryId || amount <= 0) { alert("Harap pilih kategori dan masukkan jumlah yang valid."); return; } setState(prev => { const i = prev.budgets.findIndex(b => b.categoryId === categoryId); let newBudgets = [...prev.budgets]; if (editingBudget && i > -1) newBudgets[i] = { ...editingBudget, amount }; else if (i === -1) newBudgets.push({ categoryId, amount }); else newBudgets[i] = { categoryId, amount }; return { ...prev, budgets: newBudgets }; }); setIsModalOpen(false); };
        const handleDeleteBudget = (id: string) => setState(prev => ({ ...prev, budgets: prev.budgets.filter(b => b.categoryId !== id) }));
        return (<Card><div className="flex justify-between items-center mb-4"><h3 className="text-lg font-semibold">Anggaran Bulanan</h3><Button onClick={openAddModal}><PlusIcon className="w-4 h-4 mr-1"/> Tambah</Button></div><ul className="space-y-2">{state.budgets.map(b => { const c = expenseCategories.find(c => c.id === b.categoryId); return (<li key={b.categoryId} className="flex justify-between items-center p-2 bg-slate-100 dark:bg-slate-700 rounded"><span>{c?.name}</span><div className="flex items-center gap-4"><span>{formatCurrency(b.amount)}</span><button onClick={() => openEditModal(b)}><EditIcon className="w-4 h-4 text-blue-500"/></button><button onClick={() => handleDeleteBudget(b.categoryId)}><TrashIcon className="w-4 h-4 text-red-500"/></button></div></li>)})}</ul><Modal isOpen={isModalOpen} onClose={() => setIsModalOpen(false)} title={editingBudget ? "Edit Anggaran" : "Tambah Anggaran"}><div className="p-6 space-y-4"><select value={categoryId} onChange={e => setCategoryId(e.target.value)} disabled={!!editingBudget} className="block w-full px-3 py-2 text-sm border border-slate-300 rounded-md bg-white dark:bg-slate-700 dark:border-slate-600 dark:text-white"><option value="">Pilih Kategori</option>{expenseCategories.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select><CurrencyInput value={amount} onChange={setAmount} /><Button onClick={handleSaveBudget} className="w-full">Simpan</Button></div></Modal></Card>);
    };
    const CrudSettings: React.FC<{ title: string; items: (FinancialGoal | Bill | Debt)[]; onSave: (item: any) => void; onDelete: (id: string) => void; fields: { name: string; type: 'text' | 'number' | 'currency'; label: string; min?: number; max?: number }[]; itemType: 'goal' | 'bill' | 'debt'; }> = ({ title, items, onSave, onDelete, fields, itemType }) => {
        const [isModalOpen, setIsModalOpen] = useState(false);
        const [currentItem, setCurrentItem] = useState<any>(null);
        const openModal = (item: any | null = null) => { if (item) setCurrentItem({ ...item }); else { let newItem: any = {}; if (itemType === 'goal') newItem = { name: '', targetAmount: 0, currentAmount: 0 }; else if (itemType === 'bill') newItem = { name: '', amount: 0, dueDate: 5 }; else if (itemType === 'debt') newItem = { name: '', totalAmount: 0, paidAmount: 0 }; else if (itemType === 'wallet') newItem = { name: '', balance: 0, type: 'Digital', icon: '💰' }; setCurrentItem(newItem); } setIsModalOpen(true); };
        const handleSave = () => { if (!currentItem.name) return; onSave({ ...currentItem, id: currentItem.id || `item-${new Date().getTime()}` }); setIsModalOpen(false); };
        const renderItemDetails = (item: any) => { switch(itemType) { case 'goal': return `${formatCurrency(item.currentAmount || 0)} / ${formatCurrency(item.targetAmount)}`; case 'bill': return `${formatCurrency(item.amount)} / bulan`; case 'debt': return `${formatCurrency(item.paidAmount || 0)} / ${formatCurrency(item.totalAmount)}`; case 'wallet': return `${item.type} • ${formatCurrency(item.balance)}`; default: return ''; } };
        return (<Card><div className="flex justify-between items-center mb-4"><h3 className="text-lg font-semibold">{title}</h3><Button onClick={() => openModal()}><PlusIcon className="w-4 h-4 mr-1"/> Tambah</Button></div><ul className="space-y-2">{items.map((item: any) => <li key={item.id} className="flex justify-between items-center p-2 bg-slate-100 dark:bg-slate-700 rounded"><div><p className='font-medium'>{item.name}</p><p className='text-sm text-slate-500 dark:text-slate-400'>{renderItemDetails(item)}</p></div><div className="flex items-center gap-2"><button onClick={() => openModal(item)}><EditIcon className="w-4 h-4 text-blue-500"/></button><button onClick={() => onDelete(item.id)}><TrashIcon className="w-4 h-4 text-red-500"/></button></div></li>)}</ul><Modal isOpen={isModalOpen} onClose={() => setIsModalOpen(false)} title={`${currentItem?.id ? 'Edit' : 'Tambah'} ${title}`}><div className="p-6 space-y-4">{fields.map(field => <div key={field.name}><label className="block text-sm font-medium mb-1">{field.label}</label>{field.type === 'currency' ? <CurrencyInput value={currentItem?.[field.name] || 0} onChange={val => setCurrentItem({ ...currentItem, [field.name]: val })} /> : <input type={field.type} value={currentItem?.[field.name] || ''} min={field.min} max={field.max} onChange={e => setCurrentItem({ ...currentItem, [field.name]: field.type === 'number' ? (isNaN(parseInt(e.target.value, 10)) ? '' : parseInt(e.target.value, 10)) : e.target.value })} placeholder={field.label} className="block w-full px-3 py-2 text-sm border border-slate-300 rounded-md bg-white dark:bg-slate-700 dark:border-slate-600 dark:text-white placeholder-slate-400 dark:placeholder-slate-400"/>}</div>)}<Button onClick={handleSave} className="w-full">Simpan</Button></div></Modal></Card>);
    };
    const ApiKeySettings = () => {
        const { state, updateUserSettings } = useAppContext();
        const [apiKeyInput, setApiKeyInput] = useState(state.apiKey || '');
        const [isSaving, setIsSaving] = useState(false);
        const handleSaveApiKey = async () => { setIsSaving(true); await updateUserSettings({ apiKey: apiKeyInput.trim() || null }); setIsSaving(false); alert('API Key berhasil disimpan!'); };
        return (<Card><h3 className="text-lg font-semibold mb-2">Pengaturan API Key AI</h3><p className="text-sm text-slate-500 dark:text-slate-400 mb-4">Masukkan API Key Gemini Anda untuk mengaktifkan fitur Insight AI dan Asisten Keuangan. Pengaturan Anda akan disimpan di akun Anda.</p><div className="flex items-center gap-2"><input type="password" value={apiKeyInput} onChange={(e) => setApiKeyInput(e.target.value)} placeholder="Masukkan API Key Anda" className="flex-grow block w-full px-3 py-2 text-sm border border-slate-300 rounded-md bg-white dark:bg-slate-700 dark:border-slate-600 dark:text-white placeholder-slate-400 dark:placeholder-slate-400"/><Button onClick={handleSaveApiKey} disabled={isSaving}>{isSaving ? 'Menyimpan...' : 'Simpan'}</Button></div></Card>);
    };
    const AppearanceSettings = () => {
        const layouts = [{ id: 'classic' as AppLayout, name: 'Classic' }, { id: 'modern' as AppLayout, name: 'Modern' }];
        const fonts = [{ id: 'inter' as AppFont, name: 'Inter', className: 'font-["Inter"]' }, { id: 'lora' as AppFont, name: 'Lora', className: 'font-["Lora"]' }, { id: 'poppins' as AppFont, name: 'Poppins', className: 'font-["Poppins"]' }, { id: 'mono' as AppFont, name: 'Source Code', className: 'font-mono' }];
        const accents = [{ id: 'blue' as AccentColor, name: 'Cyan Ultra', className: 'bg-[#00ffff]' }, { id: 'emerald' as AccentColor, name: 'Volt Green', className: 'bg-[#adff2f]' }, { id: 'rose' as AccentColor, name: 'Neon Rose', className: 'bg-[#ff007f]' }, { id: 'violet' as AccentColor, name: 'Electric Purple', className: 'bg-[#bf00ff]' }, { id: 'orange' as AccentColor, name: 'Neon Orange', className: 'bg-[#ffa500]' }];
        const handleToggleColorScheme = () => { const newScheme = colorScheme === 'light' ? 'dark' : 'light'; setColorScheme(newScheme); updateUserSettings({ colorScheme: newScheme }); };
        return (<Card><h3 className="text-lg font-semibold mb-2 flex items-center gap-2"><PaletteIcon className="w-5 h-5" /> Tampilan Aplikasi</h3><p className="text-sm text-slate-500 dark:text-slate-400 mb-6">Personalisasi tampilan dan nuansa aplikasi. Pilihan Anda akan disimpan di akun Anda.</p><div className="space-y-6"><div><h4 className="font-semibold text-slate-800 dark:text-slate-200 mb-2">Mode Tampilan</h4><div className="flex items-center justify-between p-3 bg-slate-100 dark:bg-slate-700/50 rounded-lg"><div className="flex items-center gap-2">{colorScheme === 'light' ? <SunIcon className="w-5 h-5 text-yellow-500" /> : <MoonIcon className="w-5 h-5 text-indigo-400" />}<span className="font-medium text-sm">{colorScheme === 'light' ? 'Mode Terang' : 'Mode Gelap'}</span></div><button onClick={handleToggleColorScheme} className="relative inline-flex h-6 w-11 flex-shrink-0 cursor-pointer rounded-full border-2 border-transparent transition-colors duration-200 ease-in-out focus:outline-none focus:ring-2 focus:ring-primary-500 focus:ring-offset-2 bg-primary-600 dark:bg-slate-600"><span className={`inline-block h-5 w-5 transform rounded-full bg-white shadow ring-0 transition duration-200 ease-in-out ${colorScheme === 'dark' ? 'translate-x-5' : 'translate-x-0'}`}/> </button></div></div><div><h4 className="font-semibold text-slate-800 dark:text-slate-200 mb-2">Layout</h4><div className="grid grid-cols-2 gap-4">{layouts.map(l => <button key={l.id} onClick={() => updateUserSettings({ layout: l.id })} className={`p-4 rounded-lg border-2 text-center font-semibold transition-all duration-200 ${activeLayout === l.id ? 'border-primary-500 ring-2 ring-primary-500/50 bg-primary-50 dark:bg-primary-900/20' : 'border-slate-300 dark:border-slate-600 hover:border-primary-500/50'}`}>{l.name}</button>)}</div></div><div><h4 className="font-semibold text-slate-800 dark:text-slate-200 mb-2">Font</h4><div className="grid grid-cols-2 md:grid-cols-4 gap-4">{fonts.map(f => <button key={f.id} onClick={() => updateUserSettings({ font: f.id })} className={`p-4 rounded-lg border-2 text-center transition-all duration-200 ${activeFont === f.id ? 'border-primary-500 ring-2 ring-primary-500/50' : 'border-slate-300 dark:border-slate-600 hover:border-primary-500/50'}`}><span className={`${f.className} text-lg`}>{f.name}</span></button>)}</div></div><div><h4 className="font-semibold text-slate-800 dark:text-slate-200 mb-3">Warna Aksen</h4><div className="flex flex-wrap gap-4">{accents.map(c => <button key={c.id} aria-label={`Setel warna aksen ke ${c.name}`} onClick={() => updateUserSettings({ accentColor: c.id })} className={`w-10 h-10 rounded-full ${c.className} flex items-center justify-center transition-all duration-200 ring-offset-white dark:ring-offset-slate-800 ${activeAccent === c.id ? 'ring-2 ring-offset-2 ring-current' : ''}`}>{activeAccent === c.id && <CheckCircleIcon className="w-6 h-6 text-white" />}</button>)}</div></div></div></Card>);
    };

    return (
        <div className="space-y-6 pb-16 md:pb-0">
            <h1 className="text-3xl font-bold text-slate-900 dark:text-white">Pengaturan</h1>
            <div className="border-b border-slate-200 dark:border-slate-700"><nav className="-mb-px flex space-x-2 sm:space-x-4 md:space-x-8 overflow-x-auto" aria-label="Tabs">{tabs.map(tab => <button key={tab.id} onClick={() => setActiveTab(tab.id)} className={`whitespace-nowrap py-4 px-2 sm:px-3 border-b-2 font-medium text-sm transition-colors ${activeTab === tab.id ? 'border-primary-600 text-primary-600 dark:border-primary-400 dark:text-primary-400' : 'border-transparent text-slate-500 hover:text-primary-600 hover:border-primary-500/50 dark:text-slate-400 dark:hover:text-primary-400 dark:hover:border-primary-400/50'}`}>{tab.label}</button>)}</nav></div>
            <div className="mt-6">
                {activeTab === 'umum' && <div className="space-y-6"><AppearanceSettings /><ApiKeySettings /><CategorySettings /></div>}
                {activeTab === 'anggaran' && <BudgetSettings />}
                {activeTab === 'target' && <CrudSettings title="Target Finansial" items={state.goals} onSave={(item) => handleSave('goals', item)} onDelete={(id) => handleDelete('goals', id)} fields={[{name: 'name', type: 'text', label: 'Nama Target'}, {name: 'targetAmount', type: 'currency', label: 'Jumlah Target'}]} itemType="goal"/>}
                {activeTab === 'dompet' && <CrudSettings title="Dompet & Akun" items={state.wallets || []} onSave={(item) => handleSave('wallets', item)} onDelete={(id) => handleDelete('wallets', id)} fields={[{name: 'name', type: 'text', label: 'Nama Dompet'}, {name: 'type', type: 'text', label: 'Tipe (Bank/Digital/Tunai)'}, {name: 'balance', type: 'currency', label: 'Saldo Saat Ini'}, {name: 'icon', type: 'text', label: 'Emoji Icon'}]} itemType="wallet" />}
                {activeTab === 'tagihan' && <CrudSettings title="Tagihan Rutin" items={state.bills} onSave={(item) => handleSave('bills', item)} onDelete={(id) => handleDelete('bills', id)} fields={[{name: 'name', type: 'text', label: 'Nama Tagihan'}, {name: 'amount', type: 'currency', label: 'Jumlah'}, {name: 'dueDate', type: 'number', label: 'Tanggal Jatuh Tempo', min: 1, max: 31}]} itemType="bill"/>}
                {activeTab === 'utang' && <CrudSettings title="Utang / Cicilan" items={state.debts} onSave={(item) => handleSave('debts', item)} onDelete={(id) => handleDelete('debts', id)} fields={[{name: 'name', type: 'text', label: 'Nama Utang'}, {name: 'totalAmount', type: 'currency', label: 'Total Pokok Utang'}]} itemType="debt"/>}
            </div>
        </div>
    );
};
